
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-07
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-07
pull_requests: [{"author":{"id":"U_kgDOCVH39Q","is_bot":false,"login":"JakindaZhang","name":""},"headRefName":"JZ-addReviewsStatus","number":26,"title":"JZ - Add moderator status column to ReviewsTable and update tests/stoâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/26"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"as-moderator-14","number":23,"title":"as - moderator review","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/23"},{"author":{"id":"U_kgDOCVH39Q","is_bot":false,"login":"JakindaZhang","name":""},"headRefName":"JZ-review-get-by-id","number":20,"title":"JZ - Add GET /api/reviews/{id} endpoint and corresponding tests for review editing","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/20"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-placeholder","number":19,"title":"yc - delete placeholder","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/19"}]
