
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-07
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-07
pull_requests: [{"author":{"id":"U_kgDOCVH39Q","is_bot":false,"login":"JakindaZhang","name":""},"headRefName":"JZ-review-get-by-id","number":20,"title":"JZ - Add GET /api/reviews/{id} endpoint and corresponding tests for review editing","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/20"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-placeholder","number":19,"title":"delete placeholder","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/19"},{"author":{"id":"U_kgDOB2QVgw","is_bot":false,"login":"IanSheinis","name":"Ian Sheinis"},"headRefName":"feat-footer","number":17,"title":"IS - Added more descriptive footer","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/17"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"as-example-to-dining","number":16,"title":"as - Example to UCSB Dining","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/16"}]
