
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-07
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-07
pull_requests: [{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-refactor-moderate-menu","number":38,"title":"Yc refactor moderate menu","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/38"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"as-mod-14","number":35,"title":"as - moderator page changed to moderator reviews page","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/35"},{"author":{"id":"U_kgDOB2QVgw","is_bot":false,"login":"IanSheinis","name":"Ian Sheinis"},"headRefName":"fix-nomealmsg","number":33,"title":"IS - Add message when there is no meal offered","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/33"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-react-eslint","number":32,"title":"Yc react eslint","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/32"},{"author":{"id":"U_kgDOCQi79A","is_bot":false,"login":"2818973981","name":"Sicheng Xu"},"headRefName":"issue30","number":31,"title":"SX- Add Admin and Moderator tables and controllers","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/31"},{"author":{"id":"U_kgDOCQi79A","is_bot":false,"login":"2818973981","name":"Sicheng Xu"},"headRefName":"issue28","number":29,"title":"SX - Add tables to support new role implementation","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/29"},{"author":{"id":"U_kgDOCQi79A","is_bot":false,"login":"2818973981","name":"Sicheng Xu"},"headRefName":"issue7","number":27,"title":"SX - Enable AUTO_SERVER=TRUE to allow multiple H2 connections","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/27"},{"author":{"id":"U_kgDOCVH39Q","is_bot":false,"login":"JakindaZhang","name":""},"headRefName":"JZ-addReviewsStatus","number":26,"title":"JZ - Add moderator status column to ReviewsTable and update tests/stoâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/26"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-placeholder","number":19,"title":"yc - delete placeholder","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-07/pull/19"}]
